### ISSUE TITLE
Domain request

### ISSUE THREAD

**Issue by HappyGuy22** [anudeepND/youtubeadsblacklist#1]
I have added your list and started seeing less ads! I have encountered some domains please add them:
r7---sn-npoe7n76r7.googlevideo.com
r2---sn-npoeen7d.googlevideo.com
r11---sn-ab5l6nes.googlevideo.com
r5---sn-aiglln7y.googlevideo.com
r2---sn-vgqs7n7k.googlevideo.com

**Comment by anudeepND** [comment]
List is now updated. Thanks for reporting. Remember to clear cache after the update
