### ISSUE TITLE
Add Domains

### ISSUE THREAD

**Issue by hellyarbm** [anudeepND/youtubeadsblacklist#2]
Added these domains by scanning through trending, which usually has most of the ads.

r18---sn-o097znes.googlevideo.com
r3---sn-n4v7sn76.googlevideo.com
r3---sn-n4v7sne7.googlevideo.com
r4---sn-n4v7sn7s.googlevideo.com

**Comment by anudeepND** [comment]
@hellyarbm sorry for the late reply :)
Thanks for reporting, I added them to the list.

**Comment by anudeepND** [comment]
Is this list working for you? Do have any problems in playing videos? How long have you been using this list?

**Comment by hellyarbm** [comment]
I have been using these for about a week. They seem to be working fine, then I read your comment and I've had two videos since not load. It may be a problem with one of these and the combination of ublock. I'll do more logging to track it down.

**Comment by anudeepND** [comment]
I faced similar problems with this list, but got a noticeable result o n [this](https://gist.githubusercontent.com/anudeepND/adac7982307fec6ee23605e281a57f1a/raw/5b8582b906a9497624c3f3187a49ebc23a9cf2fb/Test.txt) list.
Anyways user feedback is very helpful. I will close this issue for now, you can reopen it if you want.

**Comment by hellyarbm** [comment]
This sub-domain is specifically causing some videos not to load
r3---sn-n4v7sne7.googlevideo.com

**Comment by anudeepND** [comment]
Removed it from the list :)

**Comment by hellyarbm** [comment]
r3---sn-n4v7sn76.googlevideo.com is also causing some videos not to load

**Comment by mkaliyannan** [comment]
I did the same way using dnsdumpter ( which is pulled all the DNS records related to google video) . 

However, ads aren’t skipped or many videos are not playing

**Comment by mkaliyannan** [comment]
I think we can focus on privoxy with squid caching. Because YouTube embedded the ads on same url. We have to use content filter 

#### if you guys interested ### read SSL intercept, we will get something

**Comment by deathbybandaid** [comment]
@mkaliyannan this would be quite a bit out-of-scope for this experiment.
