### ISSUE TITLE
Add a hosts file

### ISSUE THREAD

**Issue by ZeroDot1** [anudeepND/youtubeadsblacklist#3]
Download: [hostfile.txt](https://github.com/anudeepND/youtubeadsblacklist/files/1428738/hostfile.txt)

**Comment by deathbybandaid** [comment]
easy enough for anybody to do

`sed 's/^/0.0.0.0 /' filename`

**Comment by ZeroDot1** [comment]
@deathbybandaid 
The file is already finished, just download it, so I converted it:  `sed 's/^/0\.0\.0\.0 /' domains.txt >> hostfile`

**Comment by wokawoka** [comment]
an hosts file is indeed really useful to be directly imported by hosts file manager utilities or ad blocking scripts on routers

**Comment by ZeroDot1** [comment]
My suggestion is to add it to the project in this way, which makes the easy use with update-hosts possible.
https://aur.archlinux.org/packages/update-hosts-git/ https://github.com/pyamsoft/update-hosts

**Comment by deathbybandaid** [comment]
I've updated the script,,, I'll give'r a run in a sec

**Comment by deathbybandaid** [comment]
@anudeepND ,,, ignore the fact that "root" pushed the changes

@ZeroDot1 @wokawoka https://github.com/anudeepND/youtubeadsblacklist/blob/master/hosts.txt

**Comment by ZeroDot1** [comment]
@deathbybandaid Thank you, Good work:)
